# Generated by Django 5.0.9 on 2026-02-21 00:03

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AventuraNivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.IntegerField(unique=True, verbose_name="número de nivel"),
                ),
                ("orden", models.IntegerField(verbose_name="orden")),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                ("descripcion", models.TextField(verbose_name="descripción")),
                ("historia", models.TextField(blank=True, verbose_name="historia")),
                (
                    "dificultad",
                    models.IntegerField(
                        choices=[(1, "Fácil"), (2, "Medio"), (3, "Difícil")],
                        default=1,
                        verbose_name="dificultad",
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        default="map-marker-alt", max_length=50, verbose_name="icono"
                    ),
                ),
                (
                    "tiempo_limite",
                    models.IntegerField(
                        default=30, verbose_name="tiempo límite (segundos)"
                    ),
                ),
                (
                    "recompensa_puntos",
                    models.IntegerField(
                        default=100, verbose_name="puntos de recompensa"
                    ),
                ),
            ],
            options={
                "verbose_name": "nivel de aventura",
                "verbose_name_plural": "niveles de aventura",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="PreguntaOrtografia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("palabra", models.CharField(max_length=100, verbose_name="palabra")),
                (
                    "palabra_correcta",
                    models.CharField(max_length=100, verbose_name="palabra correcta"),
                ),
                ("opciones", models.JSONField(verbose_name="opciones")),
                (
                    "categoria",
                    models.CharField(max_length=50, verbose_name="categoría"),
                ),
                (
                    "dificultad",
                    models.IntegerField(
                        choices=[(1, "Fácil"), (2, "Medio"), (3, "Difícil")],
                        default=1,
                        verbose_name="dificultad",
                    ),
                ),
                ("pista", models.TextField(blank=True, verbose_name="pista")),
            ],
            options={
                "verbose_name": "pregunta de ortografía",
                "verbose_name_plural": "preguntas de ortografía",
            },
        ),
        migrations.CreateModel(
            name="ProgresoOrtografia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(max_length=50, verbose_name="categoría"),
                ),
                ("aciertos", models.IntegerField(default=0, verbose_name="aciertos")),
                ("errores", models.IntegerField(default=0, verbose_name="errores")),
                (
                    "tiempo_jugado",
                    models.DurationField(
                        default=datetime.timedelta, verbose_name="tiempo jugado"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="fecha"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "progreso de ortografía",
                "verbose_name_plural": "progresos de ortografía",
            },
        ),
        migrations.CreateModel(
            name="ProgresoAventura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completado",
                    models.BooleanField(default=False, verbose_name="completado"),
                ),
                (
                    "puntuacion",
                    models.IntegerField(default=0, verbose_name="puntuación"),
                ),
                (
                    "tiempo_jugado",
                    models.DurationField(
                        default=datetime.timedelta, verbose_name="tiempo jugado"
                    ),
                ),
                (
                    "fecha_completado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha completado"
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="juegos.aventuranivel",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "progreso de aventura",
                "verbose_name_plural": "progresos de aventura",
                "unique_together": {("usuario", "nivel")},
            },
        ),
    ]
